### ISSUE TITLE
Fix subaction specific access restrictions in the customer interface.

### ISSUE THREAD

**Issue by StefanRother-OTOBO** [RotherOSS/otobo#1549] opened 2022-01-20 12:26 UTC
I get an error in the customer area if I:

1.) add a new navigation item to the customer interface, in my test including a link to  
      Action=CustomerTicketMessage;TypeID=1;ServiceID=1 and with a group restriction to group "A".
2.) The used customer is NOT in group "A".
3.) Login to the customer interface, the new item is not shown.
4.) I change to CustomerTicketMessage and choose a type. The following error occur in log (AJAX Error in frontend):

No Permission to use this frontend subaction module!

5.) If I remove old OTRS code in InterfaceCustomer, everything works fine:

                    # module permission check for submenu item
                    if (
                        ref $Item->{GroupRo} eq 'ARRAY'
                        && !scalar @{ $Item->{GroupRo} }
                        && ref $Item->{Group} eq 'ARRAY'
                        && !scalar @{ $Item->{Group} }
                        )
                    {
                        $Param{AccessRo} = 1;
                        $Param{AccessRw} = 1;
                    }
                    else {

                        ( $Param{AccessRo}, $Param{AccessRw} ) = $Self->_CheckModulePermission(
                            ModuleReg => $Item,
                            %UserData,
                        );

                        if ( !$Param{AccessRo} ) {

                            # new layout object
                            my $LayoutObject = $Kernel::OM->Get('Kernel::Output::HTML::Layout');
                            $Kernel::OM->Get('Kernel::System::Log')->Log(
                                Priority => 'error',
                                Message  => 'No Permission to use this frontend subaction module!'
                            );

                            $LayoutObject->CustomerFatalError(
                                Comment => Translatable('Please contact the administrator.')
                            );    # throws a Kernel::System::Web::Exception
                        }
                    }
                }
            }
        }

We don´t have submenu icons in OTOBO, is it possible to remove it in OTOBO 10.1 Standard?

**Comment by svenoe** [comment] 2022-01-20 13:15
We had a look on this together. I would expect the same behaviour for OTRS and assume that it is either not needed anymore, or it is a not very well implemented restriction for one specific case, e.g company tickets, and no one tried to separate frontend access and NavBar entry for stuff with necessary subactions, yet (like CTM). Someone should go through the commit history of OTRS maybe to try to find out why specifically subactions are restricted via the NavigationBar settings. (It is not present for the agent.)

**Comment by reneeb** [comment] 2022-01-28 07:34
This seems to be the relevant commit: https://github.com/znuny/Znuny/commit/6a613ab8e524888e7bfd83f1717084516b86f751 Unfortunately the bug report ist not available anymore...

**Comment by reneeb** [comment] 2022-01-28 08:14
If you remove the check for submenu items, all customers can see the content if they know the link (e.g. set a Group for company tickets, login with a user that doesn't belong to the group and visit http://your_otobo/otobo/customer.pl?Action=CustomerTicketOverview;Subaction=CompanyTickets ). So removing the check should not be an option.

**Comment by reneeb** [comment] 2022-01-28 08:19
It's hard to find a reliable and secure check... maybe do a brainstorming session.

**Comment by StefanRother-OTOBO** [comment] 2022-01-28 08:36
Hi Renée,

Thank you for your feedback! 

What I don't understand is why the check is executed when I switch to CustomerTicketMessage and then select a type. Only this AJAX request triggers the error.

Thanks a lot!

Stefan

**Comment by svenoe** [comment] 2022-01-28 08:45
It is because subactions are denied altogether, and the AJAXUpdate is one. In the end at the moment we have no streamlined way to deny access to specific subactions. For modules like AgentStats this is done in an individual way. Completely removing the above is probably not a good way, I agree with Renee, but maybe we could at least read out the Subaction of the disabled NavBar-Item, like e.g. CompanyTickets and just restrict this, because if Action=CustomerTicketOverview was restricted (basically Stefans case with CustomerTicketMessage), this can be done normally, too, and we don't need to check the NavBar at all. It's still not really clean, but it would at least allow Stefans scenario...

**Comment by reneeb** [comment] 2022-01-28 08:50
IMHO the problem is, that the navbar item Stefan mentioned, did **not** specify a subaction. If it had a subaction in the link, the check would have been skipped (https://github.com/RotherOSS/otobo/blob/0b2fd4e7a30b7e30d254fcfb1e989bb18604cb49/Kernel/System/Web/InterfaceCustomer.pm#L1274_L1275).

**Comment by svenoe** [comment] 2022-01-28 08:57
> IMHO the problem is, that the navbar item Stefan mentioned, did **not** specify a subaction. If it had a subaction in the link, the check would have been skipped (https://github.com/RotherOSS/otobo/blob/0b2fd4e7a30b7e30d254fcfb1e989bb18604cb49/Kernel/System/Web/InterfaceCustomer.pm#L1274_L1275).

Yes, but Stefan explicitely wants to not show the action itself to some people in the NavBar, but still let them create a ticket via links on the Dashboard. So I would suggest a
```
                    if (
                        $Item->{Link} !~ m/Subaction=/i
                        || $Item->{Link} !~ m/$Param{Subaction}/i
                        )
                    {
                        next ITEM;
                    }
```
at this exact position you mentioned. Because if I want to generally deny users the access to an action, it is done here: https://github.com/RotherOSS/otobo/blob/0b2fd4e7a30b7e30d254fcfb1e989bb18604cb49/Kernel/System/Web/InterfaceCustomer.pm#L1228-L1240 or am I overlooking something?

**Comment by reneeb** [comment] 2022-01-28 09:09
That could/should work...

**Comment by svenoe** [comment] 2022-02-07 13:21
I added it and will close the issue. I'm not totally happy with this initially seemingly tinkered version of access restriction in general, though.

**Closed as completed by svenoe** 2022-02-07 13:21 UTC
