### ISSUE TITLE
AgentTicketZoom 500 when opening a process ticket

### ISSUE THREAD

**Issue by ghost** [RotherOSS/otobo#3436] opened 2024-06-03 07:53 UTC
Version: 11.0.2
Browser: Google Chrome

I was using version 10.1.8, then updated it to 10.1.10 and then to 11.0.2. Now there is the following reproducible problem:
1. creating a new process ticket / opening an existing process ticket
2. error “internal server error”

I was able to find the following in the log:
`nginx_1    | 192.168.170.74 - - [03/Jun/2024:06:21:16 +0000] "POST /otobo/index.pl HTTP/2.0" 302 0 "https://otrs.XXX.de/otobo/index.pl" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36" "-"
web_1      | Can't use string ("1") as a HASH ref while "strict refs" in use at /opt/otobo/bin/psgi-bin/../../Kernel/Modules/AgentTicketZoom.pm line 1796.
nginx_1    | 192.168.170.74 - - [03/Jun/2024:06:21:17 +0000] "GET /otobo/index.pl?Action=AgentTicketZoom;TicketID=89904 HTTP/2.0" 500 21 "https://otrs.XXX.de/otobo/index.pl" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36" "-"`

I have not noticed any changes to AgentTicketZoom.pm on Github between version 10.0.18 and 11.0.2.

**Comment by OTECMarkus** [comment] 2024-06-03 11:14
I wrote wrong versions, this is correct:

I was using version 10.1.8, then updated it to 10.1.10 and then to 11.0.2. Now there is the following reproducible problem:

**Comment by OTECMarkus** [comment] 2024-06-03 11:43
I did the upgrade again, and i was able to reproduce the problem. Is it possible to downgrade, when yes - how?

**Comment by sjansen1** [comment] 2024-06-03 15:32
Did a test update to 11.0.2, all ITSM modules fails in package manager. It looks like there are no ITMS modules for 11.x

**Comment by svenoe** [comment] 2024-06-04 04:52
Hi you two,

in general with questions and problems please visit [our forums](https://otobo.io/de/forums/) for community help, github is for development topics only. Because of the recent upgrade though at least quickly:
1. Markus: AgentTicketZoom.pm underwent significant changes between the 10.0/10.1 and 11.0 version. Maybe something with your update went wrong. Please check whether you have packages installed, whether there is a file `Custom/Kernel/Modules/AgentTicketZoom.pm`, which overwrites the functionality of `Kernel/Modules/AgentTicketZoom.pm`, and directly compare your `Kernel/Modules/AgentTicketZoom.pm` to https://github.com/RotherOSS/otobo/blob/rel-11_0/Kernel/Modules/AgentTicketZoom.pm if in doubt. If everything seems right, please post your line 1796 of AgentTicketZoom.
2. sjansen: They are there, but we have an issue with the automatic update of the ChangeManagement and ConfigurationManagement, which we are aware of. In the package manager, if you select `OTOBO ITSM::Addons` (after upgrading ITSMCore, which should work out of the box) you should be able to upgrade those two from the repository list, too.

Best regards, Sven

**Comment by ghost** [comment] 2024-06-04 06:53
> Hi you two,
> 
> in general with questions and problems please visit [our forums](https://otobo.io/de/forums/) for community help, github is for development topics only. Because of the recent upgrade though at least quickly:
> 
> 1. Markus: AgentTicketZoom.pm underwent significant changes between the 10.0/10.1 and 11.0 version. Maybe something with your update went wrong. Please check whether you have packages installed, whether there is a file `Custom/Kernel/Modules/AgentTicketZoom.pm`, which overwrites the functionality of `Kernel/Modules/AgentTicketZoom.pm`, and directly compare your `Kernel/Modules/AgentTicketZoom.pm` to https://github.com/RotherOSS/otobo/blob/rel-11_0/Kernel/Modules/AgentTicketZoom.pm if in doubt. If everything seems right, please post your line 1796 of AgentTicketZoom.
> 2. sjansen: They are there, but we have an issue with the automatic update of the ChangeManagement and ConfigurationManagement, which we are aware of. In the package manager, if you select `OTOBO ITSM::Addons` (after upgrading ITSMCore, which should work out of the box) you should be able to upgrade those two from the repository list, too.
> 
> Best regards, Sven

Hello Sven, 

thanks for your quick feedback. I will create a forum entry next time.

I did not find the AgentTicketZoom.pm file in the custom folder and the code is 1:1 the same as on Github.

Here is the code from 1793 - 1806:
```
                        my $DFConfig = grep { $_->{Name} eq $Field->{Name} } $DynamicField->@*;

                        # set field
                        if ( $DFConfig->{FieldType} eq 'Set' ) {
                            $LayoutObject->Block(
                                Name => 'SetField',
                            );

                            $LayoutObject->Block(
                                Name => 'DynamicFieldSetSeparator',
                                Data => {
                                    Name => $Field->{Name},
                                },
                            );
```
Best regards
Markus

**Comment by stefanhaerter** [comment] 2024-06-04 11:33
Hi @OTECMarkus,

I just fixed the bug within pull request #3439, so it will be included in the next release. In the meantime, you can download the file ( [AgentTicketZoom.pm](https://github.com/RotherOSS/otobo/blob/rel-11_0/Kernel/Modules/AgentTicketZoom.pm) ) and copy it into your installation. I'll leave the issue open just in case any further problems arise.

Kind regards,
Stefan

**Comment by ghost** [comment] 2024-06-04 14:09
Hi @stefanhaerter thanks for the fix. I removed the AgentTicketZoom.pm and replaced it with the updated Version from you, but now i got another error message:

```
Backend ERROR: OTOBO-CGI-58 Perl: 5.38.2 OS: linux Time: Tue Jun 4 16:05:27 2024

 Message: Attempt to reload Kernel/Modules/AgentTicketZoom.pm aborted.
Compilation failed in require at /opt/otobo/bin/psgi-bin/../../Kernel/System/Main.pm line 112.


 RemoteAddress: XXX
 RequestURI: /otobo/index.pl?Action=AgentTicketZoom;TicketID=90542

 Traceback (14): 
   Module: Kernel::System::Web::InterfaceAgent::Content Line: 237
   Module: Kernel::System::Web::InterfaceAgent::Response Line: 1329
   Module: Kernel::System::Web::App::call Line: 86
   Module: Plack::Component::__ANON__ Line: 50
   Module: Plack::App::URLMap::call Line: 71
   Module: Plack::Component::__ANON__ Line: 50
   Module: Plack::Sandbox::_2fopt_2fotobo_2fbin_2fpsgi_2dbin_2fotobo_2epsgi::__ANON__ Line: 212
   Module: Plack::Sandbox::_2fopt_2fotobo_2fbin_2fpsgi_2dbin_2fotobo_2epsgi::__ANON__ Line: 182
   Module: Plack::Sandbox::_2fopt_2fotobo_2fbin_2fpsgi_2dbin_2fotobo_2epsgi::__ANON__ Line: 168
   Module: Plack::Middleware::HTTPExceptions::try {...}  Line: 20
```

```
Backend ERROR: OTOBO-CGI-58 Perl: 5.38.2 OS: linux Time: Tue Jun 4 16:03:27 2024

 Message: Can't modify numeric lt (<) in scalar assignment at /opt/otobo/bin/psgi-bin/../../Kernel/Modules/AgentTicketZoom.pm line 11, near "data"
syntax error at /opt/otobo/bin/psgi-bin/../../Kernel/Modules/AgentTicketZoom.pm line 11, near "data"
Execution of /opt/otobo/bin/psgi-bin/../../Kernel/Modules/AgentTicketZoom.pm aborted due to compilation errors.
Compilation failed in require at /opt/otobo/bin/psgi-bin/../../Kernel/System/Main.pm line 112.


 RemoteAddress: XXX
 RequestURI: /otobo/index.pl?Action=AgentTicketZoom;TicketID=90415

 Traceback (11): 
   Module: Kernel::System::Web::InterfaceAgent::Content Line: 237
   Module: Kernel::System::Web::InterfaceAgent::Response Line: 1329
   Module: Kernel::System::Web::App::call Line: 86
   Module: Plack::Component::__ANON__ Line: 50
   Module: Plack::App::URLMap::call Line: 71
   Module: Plack::Component::__ANON__ Line: 50
   Module: Plack::Sandbox::_2fopt_2fotobo_2fbin_2fpsgi_2dbin_2fotobo_2epsgi::__ANON__ Line: 212
   Module: Plack::Sandbox::_2fopt_2fotobo_2fbin_2fpsgi_2dbin_2fotobo_2epsgi::__ANON__ Line: 182
   Module: Plack::Sandbox::_2fopt_2fotobo_2fbin_2fpsgi_2dbin_2fotobo_2epsgi::__ANON__ Line: 168
   Module: Plack::Middleware::HTTPExceptions::try {...}  Line: 20

```

I cannot open normal and process tickets now.

**Comment by svenoe** [comment] 2024-06-05 06:12
Good morning Markus,

could you have a look at the file again, please. In line 11 we should still be in the commented out header, and the file compiles just fine for me. Please make sure that you copied it correctly, especially see what line 11 holds, and you might want to restart your container/apache2/... (depending on how you installed it), because at one point perl just doesn't even try to reload files anymore. (Maybe there was an error in the beginning and then your fix just isn't registered anymore: `Attempt to reload Kernel/Modules/AgentTicketZoom.pm aborted.`.)

**Comment by ghost** [comment] 2024-06-05 07:12
@svenoe there was a syntax error, i fixed it and now its working. Thanks!

**Closed as completed** 2024-06-05 07:12 UTC
Labels: bug
