### ISSUE TITLE
Customer Portal: Ticket is cut off in overview

### ISSUE THREAD

**Issue by markus-gitdev** [RotherOSS/otobo#2241] opened 2023-03-21 20:24 UTC
![grafik](https://user-images.githubusercontent.com/82206269/226731139-4f0b951f-6937-4c58-9e99-7b89483b73ee.png)

As shown in the image above, the last ticket in the overview is cut off. Would be great if that could be fixed. Either by extending the scrollable area or by just hiding the cut off ticket.

**Comment by svenoe** [comment] 2023-03-22 06:43
Hi Markus,

actually this was a conscious choice. The "last tickets" was intended to just give a quick summary, not to replace the separate ticket overview. We didn't want to load all tickets here, thus making it scrollable would suggest that there are no more tickets. Cutting it at the last completely shown ticket could do the same, and also look worse looking at the tile alignment, depending on wether there are tiles on the left and/or beneath.

If changing this behaviour will be requested by many people, we are open to rethink this decision. For now I will close the issue, though.

Best regards, Sven

**Closed as completed by svenoe** 2023-03-22 06:43 UTC
