### ISSUE TITLE
Attachment uploaded by a customer disappear after submit a ticket / response

### ISSUE THREAD

**Issue by johnnyng43** [RotherOSS/otobo#1414] opened 2021-11-16 02:39 UTC
Hi!

I saw there was an issue raised out before on the attachment upload problem in customer view #1301 , and I also encountered this situation. 
![image](https://user-images.githubusercontent.com/94419507/141885115-92255b7b-6493-4a1f-ac64-63a09fa877c2.png)

A reply said that it is due to the URL path in Apache, I tried it but the issue still happened. However, I found there is some abnormal in data level.

I'm using CentOS 8 Linux and MariaDB, and saw there is a table called "article_data_mime_attachment".  From my observation, this table save all conversation in a ticket. If an article (one of the conversation within the ticket) uplaod an attachment, 2 records can be found from this table (e.g. article_id=32 in my screen captured). The field create_by is 1 and 2 represents this article was created by customer view and agent view respectively.
![image](https://user-images.githubusercontent.com/94419507/141884878-22996efd-dfc3-4830-8d6e-e7b970441bad.png)

When customer created an article no matter it includes an attachment, only one record was inserted here. After I manual inserted a record (id=44) and refreshed the page, the attachment appears in the conversation. 
![image](https://user-images.githubusercontent.com/94419507/141884930-984ec54b-45dc-4ca6-b820-dc338aa836fc.png)

Everything looks good in agent view. I think it is not a configuration problem and I'm struggling in the source code now. Don't know why the log is not appear even I configured in Default.pm and can't trace this issue (Is it the right place?)...

    # param for LogModule Kernel::System::Log::File (required!)
    $Self->{'LogModule::LogFile'} = '/opt/otobo/logs/otobo.log';

Just wish to know anyone have the same findings as me. Thanks!

**Comment by svenoe** [comment] 2021-11-16 07:12
Hi Johnny,

as we cannot reproduce this, and the last time it occured it was a misconfiguration if I remember correctly and you also wrote, we will for now not look further into this ourselves. I can offer you some help on the debugging if you are willing to do it on your own:

If the attachment is not in the database, it means it was not properly uploaded. You can find the log of this step in a), if you are using a standard installation with apache2, the apache log (depending on your system in /var/log/apache2/error.log or I believe /var/log/httpd/error.log or so), or b) if you are using docker, by executing "docker logs otobo_web_1 --since 5m" (the 5m just as an example of course).

You can also edit the source files to get some more output, depending on what you are doing you would have to look at Kernel/Modules/CustomerTicketMessage.pm (if you are creating a new ticket), or Kernel/Modules/CustomerTicketZoom.pm (if you are answering to an existing ticket - both assuming you have no packages installed which would overwrite those files). Here my first step would be to find the block preceded by "get pre loaded attachment", and you could put some additional output to the file:

```
        # get pre loaded attachment
        my @AttachmentData = $UploadCacheObject->FormIDGetAllFilesData(
            FormID => $Self->{FormID},
        );
# dbg
use Data::Dumper
print STDERR "AttachmentData: ".Dumper(\@AttachmentData);
```


Here the attachment is stored and should be in the array. If not, the upload already failed, and you would have to look into the js (search for AjaxAttachment in var/httpd/htdocs/js/Core.UI.js - make sure to go to Admin->SysConfig in the GUI and disable Loader::Enabled::JS and clear your browser cache when editing the file) and potentially Kernel/Modules/AjaxAttachment.pm).

However, it probably is a good idea to double check your configuration before doing all this. And maybe having a look at your browser console while uploading already gives you some hint, I don't know... Let us know if you find out anything.

Best regards, Sven

**Comment by johnnyng43** [comment] 2021-11-17 01:27
Hi Sven,

Thank you for your reply and I tried to add some debug log like this:

		use Data::Dumper;
		print STDERR "CustomerTicketZoom => AttachmentData: ".Dumper(\@AttachmentData);

And I saw this message in the log after I replied with attachment:

CustomerTicketZoom => AttachmentData: $VAR1 = [];

Similarly, as agent view is normal, I also add the below logging to see its array list to compare in AgentTicketActionCommon.pm:

		use Data::Dumper;
		print STDERR "AgentTicketActionCommon => Attachments: ".Dumper(\@Attachments);

However, the array list also null, but the attachment is able to see in customer view:
AgentTicketActionCommon => Attachments: $VAR1 = [];
![image](https://user-images.githubusercontent.com/94419507/142092038-bb2ce9ad-1c7f-4fb5-902c-63b74ddfc49a.png)

Am I add the debug log in the wrong place? And from the console in chrome, I can't see any error related to the attachment. Can you provide what is the array list looks like? Maybe I have to see the permission on the upload path in the server for both customer view and agent view. Thanks.

Best regards,
Johnny

**Comment by svenoe** [comment] 2021-11-17 07:34
Ah, my mistake, sorry - I guess you have to put it one block further down behind the "# get submit attachment"-section, I just had a quick look yesterday and overlooked this.

(In general I have not really looked into this, so I'm only able to give some rough directions...)

**Comment by johnnyng43** [comment] 2021-11-17 09:09
Hi Sven,

Compared the #get submit attachment section, the code in CustomerTicketZoom.pm and CustomerTicketMessage.pm as below:
        # get submitted attachment
        my %UploadStuff = $ParamObject->GetUploadAll(
            Param => 'file_upload',
        );

For AgentTicketActionCommon.pm:
            # get submit attachment
            my %UploadStuff = $ParamObject->GetUploadAll(
                Param => 'FileUpload',
            );

Param are different between them. After I changed 2 customer pm to 'FileUpload', attachment can be shown on the webpage. I got the source code from Github few days ago, but seems the Param for customer view also 'file_upload'...
https://github.com/RotherOSS/otobo/blob/rel-10_0/Kernel/Modules/CustomerTicketZoom.pm

Why you can upload it normally?

Best Regards,
Johnny

**Comment by svenoe** [comment] 2021-11-17 10:00
Hi Johnny,

that is an interesting finding; this code is unchanged from OTRS6, though. It definitely should work with the "file_upload", too (or rather it does, normally), and it would be interesting to understand why it does not, for you.

**Comment by johnnyng43** [comment] 2021-11-17 10:09
Hi Sven,

Then the problem is still not sure…Anyway I can do what I supposed to from your hints, thank you so much!

**Comment by svenoe** [comment] 2022-04-26 10:29
As this issue is quite old now, I will close it for now. If there are any news I will reopen it if necessary.

**Closed as completed by svenoe** 2022-04-26 10:29 UTC
