### ISSUE TITLE
Checkbox Value not correct from Customer Interface

### ISSUE THREAD

**Issue by wetzf** [RotherOSS/otobo#1174] opened 2021-08-13 09:20 UTC
I added a dynamic field of type checkbox to CustomerTicketMessage and hid it with an ACL. With a different ACL I display it if a specific queue is selected. Now if i check the checkbox and submit the form, its value is stored as uncheckes (0). I would expect the value to be checked (1). 
In fact if the field is shown directly and was not hidden via an ACL the Value is stored correctly.
I could reproduce this in Version 10.0.11

**Comment by wetzf** [comment] 2021-08-13 12:38
It seems like the problem does not occur if i unset "Cache::InBackend" in SysConfig.

**Comment by stefanhaerter** [comment] 2021-08-18 10:57
I could reproduce the bug. It was due to code clearing the value of fields when they are hidden. I added a special case for the checkboxes because checkboxes work by checked-attribute, not by value. It should be fixed now.

**Closed as completed by stefanhaerter** 2021-08-18 10:57 UTC
Labels: bug
