### ISSUE TITLE
Unable to retrieve package list when using package manager 

### ISSUE THREAD

**Issue by rbr101** [RotherOSS/otobo#773] opened 2021-02-04 07:53 UTC
I'm unable to retrieve package list using a web proxy. I get the following errors:

-->
[Thu Feb  4 07:48:17 2021][Error][Kernel::System::WebUserAgent::Request][229] Can't perform POST on https://portal.rother-oss.com/otobo/public.pl: 421 Misdirected Request
[Thu Feb  4 07:48:17 2021][Error][Kernel::System::WebUserAgent::Request][229] Can't perform POST on https://portal.rother-oss.com/otobo/public.pl: 421 Misdirected Request
[Thu Feb  4 07:48:17 2021][Error][Kernel::System::WebUserAgent::Request][229] Can't perform POST on https://portal.rother-oss.com/otobo/public.pl: 421 Misdirected Request
[Thu Feb  4 07:48:19 2021][Error][Kernel::System::WebUserAgent::Request][229] Can't perform GET on https://ftp.otobo.org/pub/otobo/misc/packages/repository.xml: 421 Misdirected Request
[Thu Feb  4 07:48:19 2021][Error][Kernel::System::WebUserAgent::Request][229] Can't perform GET on https://ftp.otobo.ch/pub/otobo/packages//otobo.xml: 421 Misdirected Request
[Thu Feb  4 07:48:19 2021][Error][Kernel::System::WebUserAgent::Request][229] Can't perform POST on https://portal.rother-oss.com/otobo/public.pl: 421 Misdirected Request
[Thu Feb  4 07:48:19 2021][Error][Kernel::System::WebUserAgent::Request][229] Can't perform POST on https://portal.rother-oss.com/otobo/public.pl: 421 Misdirected Request
[Thu Feb  4 07:48:20 2021][Error][Kernel::System::WebUserAgent::Request][229] Can't perform POST on https://portal.rother-oss.com/otobo/public.pl: 421 Misdirected Request

**Comment by StefanRother-OTOBO** [comment] 2021-02-05 06:35
Dear rbr101,

i have tested the function on different systems and could not reproduce the problem. Ssllabs shows a clean SSl configuration. However, I have changed some details, can you please check the function again?

If it still doesn't work, please send us more information about the exact setup.

1.) Docker or not
2.) OTOBO version
3.) Proxy used and proxy version

As a workaround, you can also download and install all packages at https://ftp.otobo.org/pub/otobo/packages/.

Kind regards from Bavaria,

Stefan
Team OTOBO

**Comment by rbr101** [comment] 2021-02-08 13:20
Hi,

I'm using docker version in kubernetes, I just feched the lastest docker version but problem still persists.
The webproxy is a MCAFEE Webgateway. The configured option for web proxy:
Package::Proxy -> https://myproxy:8080/

Also when i try to install the package FAQ-10.0.5.opm manual, nothing happens.
I only see the text "FAQ 10.0.5" in a gray square.

**Comment by svenoe** [comment] 2021-02-08 14:17
The package not installing is a bug we are aware of, when there are problems with the above request. It will be fixed in one of the next versions of OTOBO.

**Comment by reneeb** [comment] 2022-01-07 13:35
Is this still relevant? Or was it fixed in the meantime?

**Comment by svenoe** [comment] 2022-01-10 09:07
I guess I will close it for now. This is a year old, and we played around with the packages a bit in the beginning. In the last months there were no complaints. If it is still relevant to you, @rbr101, please let us know, then I can reopen it.

**Closed as completed by svenoe** 2022-01-10 09:07 UTC
