### ISSUE TITLE
Permission denied at /opt/otobo/scripts/backup.pl line 197

### ISSUE THREAD

**Issue by micha2021** [RotherOSS/otobo#822] opened 2021-02-25 22:06 UTC
Hi! 

To create a backup I followed all steps in [https://doc.otobo.org/manual/installation/stable/en/content/backup-restore-docker.html](https://doc.otobo.org/manual/installation/stable/en/content/backup-restore-docker.html).

The command `docker run -it --rm --volume otobo_opt_otobo:/opt/otobo --volume otobo_backup:/otobo_backup --network otobo_default rotheross/otobo:latest scripts/backup.pl -d /otobo_backup` ends with this error:  `backup.pl: ERROR: Can't create directory: /otobo_backup/2021-02-25_22-01-47: Permission denied at /opt/otobo/scripts/backup.pl line 197`.

Version 10.0.9 (docker)

Best regards,
Michael

**Comment by bschmalhofer** [comment] 2021-02-26 18:16
Hi Michael,

I just tried this and it worked in my specific setup. I think that this is an effect on whether the docker admin is actually root or an user that is in the group. See https://docs.docker.com/engine/install/linux-postinstall/.

@svenoe : Could you test this with an user that is not in the docker group?

**Comment by micha2021** [comment] 2021-02-26 20:40
@bschmalhofer Hi Bernhard. As the documentation says "The Docker admin may be either the root user of the Docker host or a dedicated user with the required permissions",  I used the root user.

**Comment by bschmalhofer** [comment] 2021-03-02 16:38
Hi Michael,@micha2021,

I tried this with the user root and got the same error as you. The cause is that the backup command runs as the user 'otobo' in the Docker image. The users in the Docker image are actually users on the Docker host.  The Docker user 'otobo' is the host user with the user id 1000 and the group id 1000.  The fix is to give the backup dir to that user. Running
`chown 1000:1000 otobo_backup/` as root on the Docker host did the trick for me.

Could you try that and report your findings? If it works for you too, then I will update the instructions.

**Comment by micha2021** [comment] 2021-03-02 17:20
Hi @bschmalhofer !

Perfect. chown `1000:1000 otobo_backup/` as root helped.

But here is the next problem:

```
Backup /otobo_backup/2021-03-02_17-12-14/Config.tar.gz ... done
Backup /otobo_backup/2021-03-02_17-12-14/Application.tar.gz ... done
Dumping mysql data to /otobo_backup/2021-03-02_17-12-14/DatabaseBackup.sql.gz ...
mysqldump: Error 2020: Got packet bigger than 'max_allowed_packet' when dumping table `package_repository` at row: 2
failed
Deleting incomplete backup /otobo_backup/2021-03-02_17-12-14 ... done
```

The OTOBO installation is initial. I installed it but did not create any tickets. I just addes the necessary packets that I need for the migration (ITSM*, FAQ, Generic Catalog, MasterSlave and MultiSMTP).

Regards,
Michael

**Comment by bschmalhofer** [comment] 2021-03-02 18:58
Hi @micha2021,

this sounds good. The permissions problem is solved.

The new problem can most likely be evaded by adding the option `--max-allowed-packet 64M`  to the call of `backup.pl`. Increase the value when the problem still occurs.

For OTOBO 10.0.10 this effect should occur less often, as #648 increased the default setting.

**Comment by bschmalhofer** [comment] 2021-03-02 18:59
TODO:

- [x] update the installation manual
- [x] proofread

**Comment by bschmalhofer** [comment] 2021-03-03 15:02
The installation manual is updated, closing this issue.

**Closed as completed by bschmalhofer** 2021-03-03 15:02 UTC
Labels: bug, documentation
