### ISSUE TITLE
BUG : Email Template

### ISSUE THREAD

**Issue by iamlucas13** [RotherOSS/otobo#3726] opened 2024-08-25 18:33 UTC
Hello,

Just to forward you a bug about Email template.
If i create email template for notification i can't add attribute like <OTOBO_xxxxx>.

I think it's because <> it's for HTML. 

I tried with &lt;OTOBO_CUSTOMER_BODY[30]&gt; for example but doesn't work.

Kind regards.
Lucas

**Comment by stefanhaerter** [comment] 2024-09-06 09:14
Good morning @iamlucas13,

thank you for the report. Since you mentioned the <OTOBO_CUSTOMER_BODY> tag, I assumed that you are referring to ticket notifications. I tried to reproduce the behavior with a newly created ticket notification on the latest rel-11_0 code, but it worked fine.

Which OTOBO version did this happen on? Do you have additional packages installed?

Kind regards,
Stefan

**Comment by iamlucas13** [comment] 2024-09-07 17:58
> Good morning @iamlucas13,
> 
> thank you for the report. Since you mentioned the <OTOBO_CUSTOMER_BODY> tag, I assumed that you are referring to ticket notifications. I tried to reproduce the behavior with a newly created ticket notification on the latest rel-11_0 code, but it worked fine.
> 
> Which OTOBO version did this happen on? Do you have additional packages installed?
> 
> Kind regards, Stefan

Hello, thanks for your answer.
I mean for OTOBO ticket  notification, not for sender, but for agent. When i use html template (in notification ticket) like alert, default, unformated, i can't put tag in HTML template.

All the best.
Lucas

**Comment by stefanhaerter** [comment] 2024-09-10 11:21
Hello Lucas,

is it perhaps a possibility that you copied the tag <OTOBO_CUSTOMER_Body[30]> (note the lowercase 'Body') from the example instead of using <OTOBO_CUSTOMER_BODY[30]>?

I will provide a pull request correcting the example in the tag reference. If this isn't the case and, since the mechanism worked fine for me except when using the erroneous tag, I would kindly ask you to visit our [forums](https://otobo.io/de/forums/) for community help, or write us an email to [hello@otobo.io](mailto:hello@otobo.io) for professional support. Github is for development issues only.

All the best,
Stefan

**Comment by stefanhaerter** [comment] 2024-09-18 11:29
Update: I was able to reproduce an error once in switching cases, but this has not been reproducable reliably, so I do not see a todo here at the moment. Closing the issue.

**Closed as completed by stefanhaerter** 2024-09-18 11:29 UTC
Labels: question
