### ISSUE TITLE
Skin switch not permanent

### ISSUE THREAD

**Issue by JumpmanJunior** [RotherOSS/otobo#2172] opened 2023-02-16 11:17 UTC
We are using an additional dark skin in our Otobo installation. The agents can switch the skin in their user preferences. But switching the skin is not permanent. If the second skin is selected you are advised to refresh the page and the second skin is shown correctly. But as soon as you logout and login again the previous first skin is in use. Looking into the preferences the correct second skin is set (and it is also set correctly in the DB) but not shown. Looking into the generated HTML code I can see that the CSS files for both skins are loaded, so the incorrect one overwrites the correct one:

[head.txt](https://github.com/RotherOSS/otobo/files/10755282/head.txt)

**Comment by bschmalhofer** [comment] 2024-07-31 11:23
Hi @JumpmanJunior,

sorry for the really late reply. Last year we were busy with OTOBO 11 and some issues fell be the wayside. But now we try to catch up.

I tried to reproduce this with a Docker based installation of OTOBO 10.1.6, which was the current version on February 2023. I add ed the highcontrast skin by simply coping the default skin.

`otobo@37b9468f44e9:~$ cp -r ./var/httpd/htdocs/skins/Agent/default ./var/httpd/htdocs/skins/Agent/highcontrast`. 

This gave me a choice in the Agent Preferences frontend. I changed the skin, logged out and logged in again. The changed skin was preserved. This was also reflected in the database table `user_preferences`. 

Initially:

```
2	UserEmail	aa.bb@cc.de
2	UserMobile	
2	UserAuthBackend	
2	UserLoginFailed	0
2	UserLastLogin	1722422197
2	UserTimeZone	Europe/Berlin
```

After the change:

```
2	UserEmail	aa.bb@cc.de
2	UserMobile	
2	UserAuthBackend	
2	UserLoginFailed	0
2	UserTimeZone	Europe/Berlin
2	UserLastLogin	1722424046
2	UserSkin	highcontrast
```

So the highcontrast skin was preserved.

Your problem might have been due to an older version of OTOBO or some site specific setup. I will close this issue now. If you still have problems you can create a new issue with an indication which version of OTOBO you are using. Or you can ask in the [OTOBO Forum](https://otobo.io/forums/otobo/otobo-forum/).

**Closed as completed by bschmalhofer** 2024-07-31 11:23 UTC
Labels: invalid
