### ISSUE TITLE
The sysconfig setting "Ticket::Frontend::AgentTicketNote###StateDefault" is not taking effect.

### ISSUE THREAD

**Issue by KhalilHamada-OTOBO** [RotherOSS/otobo#2722] opened 2023-11-29 13:52 UTC
For the note, the sysconfig setting "Ticket::Frontend::AgentTicketNote###StateDefault" is not taking effect. Regardless of the status set, it remains the same.

**Comment by svenoe** [comment] 2023-11-29 17:41
This is due to https://github.com/RotherOSS/otobo/blob/d1a58db074f90f99d5d56680a3269d811dbf5717/Kernel/Modules/AgentTicketActionCommon.pm#L1891-L1899

Here for otobo 10 we should first check the approptiate Config, for otobo 11 probably take out Ticket altogether (maybe not everywhere).

(Also look for the settings in the code and remove the places where it doesn't have any effect anymore. As an explanation - the above was introduced to be able to run ACLs "correctly" before the first HTML rendering. It was not done in the best way, though.)

**Comment by stefanhaerter** [comment] 2024-01-25 07:30
I was not able to reproduce this on the latest rel-10_0. The setting seems to work fine, except if StateDefault is set to 'merged', but this was explained with the fact that this state didn't appear in the state dropdown in AgentTicketNote in the first place.

Either this has been fixed or some custom development hindered the setting. I suggest to close this unless there are additional details to consider.

Edit: The bug occurs if the ticket state has already been set, not on new tickets.

**Comment by svenoe** [comment] 2024-09-25 08:36
This is fixed in OTOBO 11. We won't change it in previous versions, as the fix has further implications, and we don't want to completely change some behaviour on existing systems.

**Closed as completed by svenoe** 2024-09-25 08:36 UTC
Labels: bug, wontfix
