### ISSUE TITLE
the same oder of a customer dashboard tile -> internal server error

### ISSUE THREAD

**Issue by OlliW** [RotherOSS/otobo#1298] opened 2021-10-04 18:28 UTC
if you configure the same oder of a customer dashboard tile, an internal server error occurred

![image](https://user-images.githubusercontent.com/80096822/135904631-3d5b1776-9b9e-4962-ab3c-cf8abea5f7ec.png)

**Comment by bschmalhofer** [comment] 2021-10-06 12:24
Hello @OlliW ,

thanks for reporting this. I think that this effect is caused by two different bugs. The first problem is that the SystemConfiguration admin page let's user to reuse already existing order values. I'll open a separate issue for that.

The second problem is the way this error is handled. There is an check for reused orders and the logmessage is sensible. But the response text to the GUI is messed up. There should be a sensible error message, not an internal server error. I did a quick search whether other pages have the same problem. Luckily it looks like the other pages handle error conditions in a saner way.

**Comment by bschmalhofer** [comment] 2021-10-06 13:55
I added a sensible error message for when the Dashboard is misconfigured. There are three config checks altogether. For testing I provoked each of the cases. Looks good. Closing this issue.

**Closed as completed by bschmalhofer** 2021-10-06 13:55 UTC
Labels: bug
