### ISSUE TITLE
backup.pl fails when source db is mysql 5.7 and destination db is mysql 8.0

### ISSUE THREAD

**Issue by OlliW** [RotherOSS/otobo#884] opened 2021-03-24 09:12 UTC
then i have to set the parameter column-statistics

![image](https://user-images.githubusercontent.com/80096822/112284363-72d67e80-8c89-11eb-8971-42a4607d4e75.png)

`mysqldump` --column-statistics=0

**Comment by bschmalhofer** [comment] 2021-03-25 09:30
Hi @OlliW ,

it looks like the problem is that on some versions of mysqldump the column-statistics feature is turned on by default. And on some versions of mysqldump this leads to an error when the table information_schema.COLUMN_STATISTICS does not exist. Under MySQL 5.7 this table usually does not exists.

As this is an effect that occurs only under specific circumstances I'm hesitant to add `--column-statistics=0` permanently to the dump command. Instead I'll add an apption for passing extra options to the dump command.  Adding a --dry-run option for printing out the dump commands seems to be useful too.

**Comment by bschmalhofer** [comment] 2021-03-25 11:15
Hi @OlliW ,

I adapted scripts/backup.pl in the branch https://github.com/RotherOSS/otobo/tree/issue-%23884-no_column_statistics . The plan is to integrate this into OTOBO 10.0.10, but we need to test first.

Best regards,
   Bernhard

**Comment by bschmalhofer** [comment] 2021-04-19 17:54
Changes are merged now. Tests are pending.

**Comment by svenoe** [comment] 2021-04-21 13:39
At least a standard migration passed.

**Closed as completed by svenoe** 2021-04-21 13:39 UTC
Labels: bug
