### ISSUE TITLE
Set no value for the boolean HTML attribute 'readonly'

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#2333] opened 2023-06-07 09:49 UTC
Boolean attributes are true if present, they require no value. But setting the attribute name as the value is fine. See https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#boolean-attributes .
My understanding is that setting no value is the better practice. In the OTOBO I have seen both variants. Thus I propose to standardize on setting no value.

The same applies to CSS. The following CSS selectors can be used: `input:not([readonly]):hover` and `input:[readonly]:hover` .

**Comment by stefanhaerter** [comment] 2023-06-21 09:31
I assume this would also apply to checked="checked", right?

**Comment by bschmalhofer** [comment] 2023-06-21 11:17
Yes, this can be done in a dedicated issue.

**Comment by bschmalhofer** [comment] 2023-06-24 10:21
The unit tests showed no new failures. PR is merged. Closing this issue.

**Comment by stefanhaerter** [comment] 2023-08-17 14:02
There are some leftovers in the css where elements are selected based upon `[readonly="readonly"]`, which (most likely, double-checking this) fails. I'll provide a PR for this soon.

**Comment by bschmalhofer** [comment] 2023-08-17 16:53
It wasn't really clear to me whether [readonly="readonly"] still matches. My impression was that it was fine, and my hope was that this isn't browser dependent.

**Comment by stefanhaerter** [comment] 2023-08-18 11:25
To be honest, I didn't think of browser dependance - I encountered the problem when setting a dynamic field readonly via ticket mask definition, which did work as expected in agent frontends, but (at least the css) not in customer frontend despite the field having the correct class and getting the readonly attribute. Maybe the problem is that my installed version of firefox appends to the readonly and checked attributes: readonly` in tt file becomes `readonly=""` in browser inspector. I assumed that this was the solution, that `[readonly="readonly"]` does not match `readonly=""` - also, there are cases of `[readonly=readonly]`, I currently do not know if the double quotes make a difference, but I thought the easiest solution would be to unify this also in CSS, but now I am not 100% sure anymore - what do you think?

**Comment by bschmalhofer** [comment] 2023-08-18 17:05
Unifying it in the CSS should be done anyways, as it reduces confusion. Looking at the Spec I found that only the existence of the attribute matters, so even readonly="0" should set the attribute.

**Comment by stefanhaerter** [comment] 2023-08-19 07:25
Thank you for checking =) I'll do the changes then.

**Comment by stefanhaerter** [comment] 2023-08-19 18:24
@bschmalhofer Do you think the issue can be closed again?

**Comment by bschmalhofer** [comment] 2023-08-19 19:37
Yes, I'm closing the issue again.
 I was wondering why I didn't close automatically, as you had put a 'Closing' comment in the PR.

**Comment by stefanhaerter** [comment] 2023-08-20 18:07
As far as I know, there isn't really some kind of closing mechanism - I keep adding the references to the PRs and vice versa so that, if I return to either one later on, I don't have to research which PR or which issue was related but can simply click a link 😅 So it is merely a matter of me being lazy.

**Comment by stefanhaerter** [comment] 2024-06-19 11:14
I found some leftovers of `disabled="disabled"`. Is this supposed to be also changed to `disabled` or are there objections?

**Comment by stefanhaerter** [comment] 2024-07-05 12:01
Moving the previous comment to a new issue for better distinction.

**Closed as completed by stefanhaerter** 2024-07-05 12:01 UTC
Labels: tidying
