### ISSUE TITLE
placeholder ckeditor customer interface

### ISSUE THREAD

**Issue by joserribeiro26** [RotherOSS/otobo#1035] opened 2021-05-27 17:15 UTC
When we disable the Frontend::Rich Text setting, the customer portal appears to have a problem with the Class placeholder.
See the image below.

![image](https://user-images.githubusercontent.com/475022/119868631-aafe7580-bef5-11eb-8112-bf71a763b50a.png)

**Comment by joserribeiro26** [comment] 2021-05-27 17:15
![image](https://user-images.githubusercontent.com/475022/119868877-fca70000-bef5-11eb-9c29-22d10491acdd.png)

**Comment by svenoe** [comment] 2021-05-28 09:31
Thanks for letting us know. We will have to include this correctly to the css and possibly js.

**Comment by reneeb** [comment] 2022-01-07 13:24
This seems to be fixed in the meantime. At least in 10.1 beta1 I could reproduce the error...

**Comment by svenoe** [comment] 2022-01-10 09:03
> This seems to be fixed in the meantime. At least in 10.1 beta1 I could reproduce the error...

"could *not*" I guess. Yes, we introduced quite some changes for the dynamic field generation between 10.0 and 10.1. This came up somewhere in another issue and I forgot about this one. It is fixed at least in 10.1, I'm closing the issue.

**Closed as completed by svenoe** 2022-01-10 09:03 UTC
Labels: bug
