### ISSUE TITLE
JavaScript not available - Blocked script execution

### ISSUE THREAD

**Issue by nandaccio** [RotherOSS/otobo#492] opened 2020-09-29 21:27 UTC
We are experiencing the following errors as soon as a reply is available:
![otobo](https://user-images.githubusercontent.com/13116598/94618131-f13dff00-02aa-11eb-9189-8ff8a6d07b37.png)

JavaScript is obviously enabled in the browsers (we tried on different browsers, different machines, different OS), so we are not sure if it's something that must be changed in the configuration.

**Comment by svenoe** [comment] 2020-09-30 06:10
I assume you are using otobo via http, while still having https configured as default http type. Please go to the SysConfig, look for "HttpType", and change it, if I am right.

(We are going to change this in one of the next versions, to make it more obvious somehow. If my assumption is right, this is a duplicate of #475.)

**Closed as completed** 2020-10-12 07:34 UTC
Labels: duplicate
