### ISSUE TITLE
DynamicField Database + ACL Form: value seems empty

### ISSUE THREAD

**Issue by StefanAbel-OTOBO** [RotherOSS/otobo#2158] opened 2023-02-09 10:01 UTC
When creating a DF Database and hiding it with an ACL (Possible Not > Ticket Form) under some circumstances, it seems empty when displaying it again.

Step 1: Create a DF Database and make it work
![image](https://user-images.githubusercontent.com/87359203/217779549-dfe7970f-18f7-4fad-9b37-290ef5642e40.png)

Step 2: Create two ACLs to hide the DF Database in some situations (here depending on the Ticket Type "RfC")
![image](https://user-images.githubusercontent.com/87359203/217779636-80ba3555-290f-409a-bd1c-5ed00ed436c9.png)
and
![image](https://user-images.githubusercontent.com/87359203/217779704-8ef65781-0c1f-424f-bb6e-09794215e560.png)

Step 3: Create a ticket with a value in the DF Database
![image](https://user-images.githubusercontent.com/87359203/217778931-4616aa93-d74c-48f7-8c64-e56201bc990b.png)

Step 4: Change the prerequesite so that the DF Database will be hidden according to your ACL (here: change the Type to not "RfC" and save it
![image](https://user-images.githubusercontent.com/87359203/217779104-a0ad53e6-83d8-49e3-a636-3dc4f1e9896f.png)
and
![image](https://user-images.githubusercontent.com/87359203/217779974-ef7bd8f2-6ed4-46bc-89da-12ff1ea5da33.png)
You see that the DF disappears from the window, but it still has its value (which is the correct behaviour)
![image](https://user-images.githubusercontent.com/87359203/217780146-13ec63c8-86a7-4d16-8a8c-6a782e441b4d.png)

Step 5: Change the  prerequesite so that the DF Database will be shown again according to your ACL (here: change the Type to "RfC" and see that in this window, the DF appears again - but without any value.
![image](https://user-images.githubusercontent.com/87359203/217780425-29cdccd6-28c6-4fc9-b526-2abef610d0d8.png)
You don't see a value in the DF, despite the fact that it has one (according to the Ticket History and the Ticket Information).
If you would now click on "Submit", it would delete the value, which might cause quite the problems if you still expect your value.
![image](https://user-images.githubusercontent.com/87359203/217780757-b5c1dcbb-676e-4927-8e87-76f23e89126f.png)

My expectation would be that if you show the field again, it should display it's stored value.

**Comment by StefanAbel-OTOBO** [comment] 2023-02-09 10:04
ov139 10.1.6

**Comment by svenoe** [comment] 2023-02-09 11:55
For dynamic fields which do not have a default value, hiding them and then showing them again is supposed to empty them. To me your description sounds like it works as intended. Only with "You see that the DF disappears from the window, but it still has its value (which is the correct behaviour)" I don't understand why you write that "it still has its value"?

**Comment by StefanAbel-OTOBO** [comment] 2023-02-14 16:15
but when you show it and it already has a value stored, imho that stored value should be shown in the DF. In case this is intended, I feel okay with closing the bug, but for me it doesn't feel like the correct behaviour.

**Comment by stefanhaerter** [comment] 2024-07-04 06:02
Is the discussion on this topic still open or can this issue be closed?

**Comment by stefanhaerter** [comment] 2024-10-01 12:51
Nothing new so far, closing the issue.

**Closed as completed by stefanhaerter** 2024-10-01 12:51 UTC
Labels: bug, duplicate
