### ISSUE TITLE
Suggestion: Add function AddCSSData

### ISSUE THREAD

**Issue by stefanhaerter** [RotherOSS/otobo#2416] opened 2023-07-25 08:06 UTC
The file `Kernel/Output/HTML/Layout/Template.pm` already provides the function [`AddJSData`](https://github.com/RotherOSS/otobo/blob/152bb89910b1b09f97dd609eece157b991f19719/Kernel/Output/HTML/Layout/Template.pm#L358-L367) for dynamically adding JS data to the Layout object. If possible, I think it would be a nice enhancement to have an analogous function `AddCSSData` for the purpose to dynamically add style code. My current use case is to dynamically provide coloring for deployment states of config items.

**Comment by bschmalhofer** [comment] 2023-07-26 20:21
Actually I think that `AddJSData()` is overused and using data-attributes would be a better pattern. See #2372. However I can't tell how that applies to CSS styles. My gut feeling is that I dynamic styles can be considered as part of the generated HTM and not as some kind of separate data.

**Comment by bschmalhofer** [comment] 2023-10-26 16:26
Closing, as the issue is under triage.

**Closed as completed by bschmalhofer** 2023-10-26 16:26 UTC
