### ISSUE TITLE
ERROR:  invalid input syntax for type bigint: "9910/image001.jpg@01DAC89A.E2CE7170"

### ISSUE THREAD

**Issue by escix** [RotherOSS/otobo#3575] opened 2024-07-05 01:32 UTC
Getting this error in otobo.log.
Likely something to do with the postgresql database, not sure.

2024-07-05 09:55:35 |   | [Fri Jul  5 09:55:35 2024][Error][Kernel::System::Ticket::TicketGet][1266] ERROR:  invalid input syntax for type bigint: "9910/image001.jpg@01DAC89A.E2CE7170"

2024-07-05 09:55:35 |   | [Fri Jul  5 09:55:35 2024][Error][Kernel::System::Ticket::TicketGet][1266] ERROR:  invalid input syntax for type bigint: "9910/image001.jpg@01DAC89A.E2CE7170"

2024-07-05 09:55:35 |   | [Fri Jul  5 09:55:35 2024][Error][Kernel::System::Ticket::TicketFlagGet][7360] ERROR:  invalid input syntax for type bigint: "9910/image001.jpg@01DAC89A.E2CE7170"

**Comment by bschmalhofer** [comment] 2024-07-05 08:29
I took a quick look at the code in rel-11_0.

- https://github.com/RotherOSS/otobo/blob/6d6cd0ba9c1734b06796d41558bd242bf49b735c/Kernel/System/Ticket.pm#L1256
- https://github.com/RotherOSS/otobo/blob/6d6cd0ba9c1734b06796d41558bd242bf49b735c/Kernel/System/Ticket.pm#L7355

In both case it is an SQL statement where `$Param{TicketID}` is used as a bind variable. This pararmeter should be an integer, I have no idea how TicketID could obtain a value like  "9910/image001.jpg@01DAC89A.E2CE7170". The other unknown is whether MySQL and MariaDB silently accept this strange value and only PostgreSQL complains.

@escix:
Could you report your version of OTOBO and whether you can view the ticket with the ID 9910.

**Comment by stefanhaerter** [comment] 2024-07-05 08:31
Perhaps the erroneously TicketID is related to https://github.com/RotherOSS/otobo/issues/3569 - but I couldn't reproduce this.

**Comment by bschmalhofer** [comment] 2024-07-05 10:25
@stefanhaerter  Could you test with MySQL and an adapted version ot Ticket.t ?

```
$ git diff
diff --git a/scripts/test/Ticket.t b/scripts/test/Ticket.t
index a398a78b90..4fd8ee7e4d 100644
--- a/scripts/test/Ticket.t
+++ b/scripts/test/Ticket.t
@@ -70,7 +70,7 @@ $Self->True(
 );
 
 my %Ticket = $TicketObject->TicketGet(
-    TicketID => $TicketID,
+    "$TicketID/image001.jpg@01DAC89A.E2CE7170",
     Extended => 1,
 );
 $Self->Is(

```

**Comment by stefanhaerter** [comment] 2024-07-05 10:59
Confirmed, error does not appear with MariaDB.

**Comment by escix** [comment] 2024-07-05 23:36
> I took a quick look at the code in rel-11_0.
> 
> * https://github.com/RotherOSS/otobo/blob/6d6cd0ba9c1734b06796d41558bd242bf49b735c/Kernel/System/Ticket.pm#L1256
> * https://github.com/RotherOSS/otobo/blob/6d6cd0ba9c1734b06796d41558bd242bf49b735c/Kernel/System/Ticket.pm#L7355
> 
> In both case it is an SQL statement where `$Param{TicketID}` is used as a bind variable. This pararmeter should be an integer, I have no idea how TicketID could obtain a value like "9910/image001.jpg@01DAC89A.E2CE7170". The other unknown is whether MySQL and MariaDB silently accept this strange value and only PostgreSQL complains.
> 
> @escix: Could you report your version of OTOBO and whether you can view the ticket with the ID 9910.

OTOBO 11.0.2
Yes, I can view the ticket but without the images unfortunately. It also takes a little longer to load the ticket, maybe looking for the image.

**Comment by escix** [comment] 2024-07-05 23:38
> Perhaps the erroneously TicketID is related to #3569 - but I couldn't reproduce this.

yes it is.

**Comment by stefanhaerter** [comment] 2024-07-16 12:58
Closing the issue, see https://github.com/RotherOSS/otobo/issues/3594#issuecomment-2230826775

**Closed as completed by stefanhaerter** 2024-07-16 12:58 UTC
