### ISSUE TITLE
Search fields in TicketSearch are case sensitive

### ISSUE THREAD

**Issue by niccord** [RotherOSS/otobo#1091] opened 2021-06-17 16:24 UTC
As the title says, the fields of the Kernel::System::Ticket::TicketSearch::TicketSearch subroutine are case sensitive.
Make it case insensitive.

**Comment by stefanhaerter** [comment] 2021-06-25 08:34
Hi niccord,

I'm currently investigating the issue. Are you able to provide any further details, like the release version? I'm not able to reproduce the behaviour in rel-10_0. I tested the fields 'Title', 'Text', 'From' and 'Subject'.

Kind regards,
Stefan

**Comment by reneeb** [comment] 2022-01-07 13:21
Which database system do you use? And can you describe a test case more detailed?

**Comment by niccord** [comment] 2022-01-07 15:22
I found this issue using MySQL and otobo version 10.0.9.

Below you can find the code to reproduce it: copy and paste it inside the `bin` folder, then execute `perl bin/test.pl` via terminal:
``` perl
#!/usr/bin/env perl

use strict;
use warnings;
use utf8;
use feature qw(say);

use File::Basename qw(basename dirname);
use FindBin qw($RealBin);
use lib dirname($RealBin);
use lib dirname($RealBin) . '/Kernel/cpan-lib';

use Kernel::System::ObjectManager;
local $Kernel::OM = Kernel::System::ObjectManager->new(
  'Kernel::Language' => {
    LogPrefix => 'OTOBO-test.pl',
  },
);
my $TicketObject  = $Kernel::OM->Get('Kernel::System::Ticket');
my @TicketList = $TicketObject->TicketSearch(
  Result          => 'ARRAY',
  SortBy          => 'Age',
  OrderBy         => 'Down',
  Title           => '%PASSword%',
  UserID          => 1,
);
foreach (@TicketList) {
  say $_;
}
```

A ticket with the title "change my password" will not be printed as a result.
The issue is not there in my dev environment as @stefanhaerter probably meant in his previous comment.

**Comment by reneeb** [comment] 2022-01-07 15:37
What's the collation of the ticket table?

**Comment by reneeb** [comment] 2022-01-07 15:39
`LIKE` is by default case insensitive. When something is binary (like some collations, or  `LIKE BINARY '%...%'`), then it is case sensitive... There might be other reasons that causes case sensitive queries as well.

**Comment by niccord** [comment] 2022-01-07 15:47
Ok, here's probably where the issue lies:

**Local env, case insensitive**
Charset: utf8mb4
Collation: utf8mb4_unicode_ci

**Remote env, case sensitive**
Charset: utf8
Collation: utf8_bin

**Comment by reneeb** [comment] 2022-01-07 15:52
Yes, _utf8\_bin_ causes `LIKE` to be case sensitive... Can you change the collation and check again?

**Comment by niccord** [comment] 2022-01-07 16:12
Changing the collation of the column to `uft8mb4_unicode_ci` resolved the issue.
Why was my database created with those charset and collation?

**Comment by reneeb** [comment] 2022-01-07 16:17
That's a miracle ;-) Check the mysql config if that's the default for new databases.

I'm going to close the issue if you're ok with it...

**Closed as completed** 2022-01-07 16:42 UTC
