### ISSUE TITLE
Lens on dynamic field Database does not work (well)

### ISSUE THREAD

**Issue by stefanhaerter** [RotherOSS/otobo#3793] opened 2024-09-19 06:37 UTC
There seem to be a few problems when using a dynamic field Database as attribute field for a dynamic field lens, e.g. erroneous edit field render and search value handling as well as AJAX error when opening an AgentTicketActionCommon mask.

**Comment by svenoe** [comment] 2024-09-25 09:33
Duplicate of #3534

**Closed as completed by svenoe** 2024-09-25 09:33 UTC
Labels: bug, duplicate
