### ISSUE TITLE
Mobile view: editing ACLs not possible

### ISSUE THREAD

**Issue by StefanAbel-OTOBO** [RotherOSS/otobo#2020] opened 2022-11-30 15:31 UTC
When you are in mobile view and want to edit an existing ACL in Action=AdminACL;Subaction=ACLEdit , there is no "Save"-Button. You neither find it below the ACL:
![image](https://user-images.githubusercontent.com/87359203/204839586-a9b1dd7c-38b9-4180-809b-3e9311217ec0.png)

... nor can you find it in the menu on the right:
![image](https://user-images.githubusercontent.com/87359203/204839693-97d63564-d3e0-46d4-86fb-8539df7fbd5e.png)

This means that currently it is not possible to edit any ACL on a mobile device.

**Comment by stefanhaerter** [comment] 2022-12-01 08:42
I can confirm this. The saving widget appears at a screen width of 1025px and beyond, which - as far as my tests showed - is caused by the widget having the `ScreenXL` class instead of the `Expanded` class like the other widgets. Before changing this, I would like to discuss possible intentions for setting this class and potential side effects.

**Comment by stefanhaerter** [comment] 2022-12-01 10:06
PR merged, closing this as complete.

**Closed as completed by stefanhaerter** 2022-12-01 10:06 UTC
Labels: style
