### ISSUE TITLE
[BUG] Can't locate Kernel/Autoload/Znuny4OTOBOPasswordPolicy.pm

### ISSUE THREAD

**Issue by thomasboehm** [RotherOSS/otobo#3974] opened 2024-12-09 13:13 UTC
### Environment

- Server OS Distribution: Ubuntu 22.04.5 LTS
- OTOBO installation typ: Nativ Apache
- Browser: n.a.
- OTOBO version: 11.0.7
### Expected behavior

Update from 10.1.6 to 11.0.7 should run without errors when following the official update instructions.

During an updade from 10.1.6 to 11.0.7 I ran DBUpdate-to-11.0.pl and got the following errors

```
 Migration started ... 
        Executing task 'Add frontend_mask_definition table.' ... 
ERROR: Can't locate Kernel/Autoload/Znuny4OTOBOPasswordPolicy.pm in @INC (you may need to install the Kernel::Autoload::Znuny4OTOBOPasswordPolicy module) (@INC contains: /opt/otobo-11.0.7/Custom /opt/otobo-11.0.7/Kernel/cpan-lib /opt/otobo-11.0.7 /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.34.0 /usr/local/share/perl/5.34.0 /usr/lib/x86_64-linux-gnu/perl5/5.34 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl-base /usr/lib/x86_64-linux-gnu/perl/5.34 /usr/share/perl/5.34 /usr/local/lib/site_perl) at /opt/otobo-11.0.7/Kernel/Config/Defaults.pm line 2429.
!
        Executing task 'Add set and value indices to dynamic_field_value; change its id to BIGINT.' ... 
        Executing task 'Add script field event table.' ... 
        Executing task 'Add tables for the ImportExport feature.' ... 
        Executing task 'Update the list of installed packages' ... 
        Executing task 'Add translation_item table.' ... 
        Executing task 'Add form_cache table.' ... 
        Executing task 'Add preselected_state_id to standard_template.' ... 
        Executing task 'Add article version tables and add article edit ticket history types.' ... 
        Executing task 'Update Customer color definitions.' ... 
ERROR: Can't locate Kernel/Autoload/Znuny4OTOBOPasswordPolicy.pm in @INC (you may need to install the Kernel::Autoload::Znuny4OTOBOPasswordPolicy module) (@INC contains: /opt/otobo-11.0.7/Custom /opt/otobo-11.0.7/Kernel/cpan-lib /opt/otobo-11.0.7 /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.34.0 /usr/local/share/perl/5.34.0 /usr/lib/x86_64-linux-gnu/perl5/5.34 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl-base /usr/lib/x86_64-linux-gnu/perl/5.34 /usr/share/perl/5.34 /usr/local/lib/site_perl) at /opt/otobo-11.0.7/Kernel/Config/Defaults.pm line 2429.
!
        Executing task 'Try integrating the new customer dashboard info tile.' ... 
          No activated tiles of order 4, 6 or 7 - skipping.
Cannot find encoding "console_out" at /opt/otobo-11.0.7/Kernel/System/Encode.pm line 94 during global destruction.
```
Apart from this everything seems to run fine. I only get an email about this every 5 minutes.
There is a closed issue [here](https://github.com/RotherOSS/otobo/issues/987) about removing "Znuny4OTOBOPasswordPolicy.pm". Why is it still trying to load that module?

To supress the email every 5 minutes I copied the module from the old installation into the folder.

### How to reproduce
Follow the updade instructions from https://doc.otobo.org/manual/installation/11.0/en/content/updating.html
At step 6 run /opt/otobo/scripts/DBUpdate-to-11.0.pl

**Comment by svenoe** [comment] 2024-12-10 08:35
Hi Thomas,
this is likely not a bug, we have had too many upgrades without that happening. For some reason there is probably still an old SysConfig option running, or so. If your packages are all upgraded correctly you could try a `bin/otobo.Console.pl Maint::Config::Rebuild --cleanup`. If this doesn't fix it, please either seek for community help in our [forums](https://otobo.io/forums/otobo/otobo-forum/), or write an email to hello@otobo.io for professional support. I'll close the issue in the meantime. If you find the reason and still think it is a bug, please comment here, again.
Best regards, Sven

**Closed as completed by svenoe** 2024-12-10 08:35 UTC

**Comment by thomasboehm** [comment] 2024-12-10 10:38
> bin/otobo.Console.pl Maint::Config::Rebuild --cleanup

Thanks, this seems to have fixed it.
